### ISSUE TITLE
Expose `spec` values?

### ISSUE THREAD

**Issue by shinebayar-g** [cdk8s-team/cdk8s-core#974] opened 2023-01-06 00:48 UTC
In Pulumi or even Terraform, it's possible to make references to `.spec` body. Looks like it's not possible to do this with cdk8s. For example:
```ts
const deploy = new KubeDeployment(this, 'deployment', {
    spec: {
        replicas: 2,
        selector: {
            matchLabels: label,
        },
        template: {
            metadata: { labels: label },
            spec: {
                containers: [
                    {
                        name: 'hello-kubernetes',
                        image: 'paulbouwer/hello-kubernetes:1.7',
                        ports: [{ containerPort: 8080 }],
                    },
                ],
            },
        },
    },
});

const svc = new KubeService(this, 'service', {
    spec: {
        type: 'LoadBalancer',
        ports: [{ port: 80, targetPort: IntOrString.fromNumber(8080) }], // We're kinda hardcoding port value here
        selector: label,
    },
});
```

instead we could do something like this if `.spec` is available

```ts
const svc = new KubeService(this, 'service', {
    spec: {
        type: 'LoadBalancer',
        ports: [{ port: 80, targetPort: deploy.spec.template.spec.containers[0].ports[0] }],
        selector: label,
    },
});
```

This serves 2 purposes,
1. Make implicit dependency between resources. In this case service is dependent on deployment.
2. Avoid hardcoding values as much as possible.

Is this technically possible to achieve this? Or it's not possible at all?

**Comment by iliapolo** [comment] 2023-01-11 08:57
@shinebayar-g See https://github.com/cdk8s-team/cdk8s/issues/918#issuecomment-1378423591

**Comment by iliapolo** [comment] 2023-01-11 08:59
Duplicate of https://github.com/cdk8s-team/cdk8s/issues/2174

**Closed as completed** 2023-12-21 06:43 UTC
Labels: duplicate, feature-request, priority/p2, effort/large
